# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: "EssentialsSpawn"

main: "${group}.spawn.EssentialsSpawn"

version: ${version}
website: ${website}
description: ${description}

depend: [Essentials]

authors: [Ryder Belserion, Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, SupaHam, mdcfe, DoNotSpamPls, JRoy]

api-version: "1.13"

commands:
  setspawn:
    description: Sets the spawn point to your current position.
    usage: /<command> <group>
    aliases: [esetspawn]
  spawn:
    description: Teleports to the spawn point.
    usage: /<command> [player]
    aliases: [espawn]

permissions:
  essentials.spawn-on-join.exempt:
    default: false
    description: "Bypass spawn teleportation on join when spawn-on-join is true."