# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: "EssentialsChat"

main: "${group}.chat.EssentialsChat"

version: ${version}
website: ${website}
description: ${description}

softdepend: [Vault, LuckPerms]

depend: [Essentials]

authors: [Ryder Belserion, Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Okamosy, Iaccidentally, mdcfe, JRoy, triagonal]

api-version: "1.13"

commands:
  toggleshout:
    description: Toggles whether you are talking in shout mode
    usage: /<command> [player] [on|off]
    aliases: [etoggleshout]

permissions:
  essentials.chat.local:
    default: true
  essentials.chat.receive.local:
    default: true
  essentials.chat.receive.shout:
    default: true
  essentials.chat.receive.question:
    default: true
